### ISSUE TITLE
Error during install with Python 3.6

### ISSUE THREAD

**Issue by anapaulagomes** [sixty-north/cosmic-ray#202]
I'm using Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) with venv and during the install cosmic-ray install process, I got this message:

```
pip install cosmic-ray
Collecting cosmic-ray
  Using cached cosmic_ray-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zd/j6v5hs9n04d53y00f2y9qnnw0000gn/T/pip-build-0wfnlxqf/cosmic-ray/setup.py", line 4, in <module>
        long_description = readme.read()
      File "/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in dec
ode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 433: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zd/j6v5hs9n04d53y00f2y9qnnw0000gn/T/pip-build-0wfnl

xqf/cosmic-ray/
```

The lib have support to py36? Thanks.

**Comment by abingham** [comment]
It should work with 3.6, but the pypi version is probably out of date. Can
you try installing from source? If that works, then I'll make a note to
update pypi soon.

**Comment by abingham** [comment]
Actually, that looks like a really old version (0.1.2). Is that cached from a while back or something?

**Comment by abingham** [comment]
Err...never mind. That's definitely the one coming from pypi.

**Comment by anapaulagomes** [comment]
I would appreciate an update on pypi! I was able to install from the source code (after solve a lot of problems with dependencies). A suggestion: add a requirements.txt file or a bullet list. It'll make more easy to other developers to see the dependencies around the project. Thanks!

**Comment by abingham** [comment]
I'm really confused by this bug. Now that I've had some time to really look at it (sorry, I was in a hurry earlier), the version you seem to be getting from pip is wrong. The code it's executing in `setup.py` isn't in the version that pypi should be serving up. Is it possible that you're reading from a private package server or something?

In any event, I'll push up a new pypi version soon.

> I was able to install from the source code (after solve a lot of problems with dependencies).

Can you describe the problems you encountered? The `python setup.py install` should take care of everything, so I need to know if there are problems with that approach.

> A suggestion: add a requirements.txt file or a bullet list

I'm not sure what a `requirements.txt` will tell developers that the current `setup.py` doesn't. In my experience, the main use for `requirements.txt` is to specify exact versions of dependencies that are known to work, but this is primarily useful if those version can get priority. Since CR is normally installed into the environments of *other* applications/packages (i.e. the code under test), it can't in general demand specific versions lest it conflict with that code. I'm willing and happy to be convinced that a `requirements.txt` would be useful, but you'll have to explain how it improves upon `setup.py`.

**Comment by abingham** [comment]
@anapaulagomes Can I close this?
