### ISSUE TITLE
RFC: mutation operator to discover side-effects

### ISSUE THREAD

**Issue by atodorov** [sixty-north/cosmic-ray#204]
I think we can all agree that side-effects from functions/methods can be a great source of bugs, mostly due to poor knowledge/understanding of said side-effects from developers using said functions. 

What do you think about a mutation operator which helps discover those. I'm thinking about an operator which will duplicate function calls, maybe also object creations. For example:
`s = sum(a, b)` will become 
```
s = sum(a, b)
s = sum(a, b)
```

If this function has a side effect calling it twice could change the system state in an unpredictable fashion.

I'm only concerned that this may generate failures which will signal to Cosmic-Ray that the test suite failed, meaning mutant was killed.

What do others think ?

**Comment by abingham** [comment]
I think the concept is interesting, but I'm not sure that cosmic ray (as
currently envisioned) is the right tool for it. Taken at face value, this
seems like a recipe for a lot of survivors. If sum() really *is* pure, then
duplicating that call would almost certainly result in a passing test
suite, i.e. it would be almost impossible and definitely unreasonable to
have a test that would detect such a change.

With that said, I could imagine (without having thought about it a whole
lot) that cosmic ray could be a more general tool for mutating code.
Mutation testing would be one application of it, but it CR could also be
used to do the kind of thing you're talking about. I'm not advocating that
we do that right now, but it is an interesting thing to think about.

So I guess my view is that the operator you're talking about doesn't have
much of a place in CR right now. However, since you should be able to add
operators via plugins there's nothing (in principle) stopping you from
creating and using it if you want.
