### ISSUE TITLE
Add exception mutations

### ISSUE THREAD

**Issue by drorasaf** [sixty-north/cosmic-ray#206]
One of the common issues I've seen in code is the exception handling which tends to be non selective.
This can be verified with mutation over the exceptions which are raised.

What do you say about adding it to CR?

**Comment by atodorov** [comment]
What exactly do you mean ? Changing `raise SomeException` to `raise AnotherException` ?? Can you give an example? 

I think the idea is good but I need more details so we can discuss. 

Btw check out this video. It talks about research on exception/error handling code and mentions several very common mistakes. It's been on my todo list for quite a while but I haven't gotten the time to work on it:
https://www.youtube.com/watch?v=56oNQf5oITw&t=785s&list=PLFjlI7p-h1hxBP3cIjEqePSeoBDHud5Db&index=55

My initial idea was to add something in pylint which will detect above mentioned patterns but maybe we can implement some of there into CR.

**Comment by abingham** [comment]
As @atodorov said, it sounds to me like you're suggesting a mutation operator which modifies which exceptions are thrown in the mutated code. I think that could be a very useful class of mutation operators! Are you willing to try implementing it? 

Creating new mutation operators should be relatively simple with our plugin system. In fact, you could do it in a separate package to start with if you want. We can work with you on it to make sure you don't get hung up on too many snags.

**Comment by drorasaf** [comment]
@atodorov , The idea is to mutate with the following options:
1. `raise ChildException` to `raise ParentException`
2. `raise SomeException` to `raise TotallyAnotherException`
3. switch between:
`raise SomeException
....
 raise AnotherException`
 to change into:
`raise AnotherException 
....
raise SomeException`

I think pylint is nice, but I'm not sure it can detect these kind of issues.

@abingham ,I will do as you suggested I will try to implement it myself in another repo. Thanks!

**Comment by atodorov** [comment]
@drorasaf a few notes/comments

* `raise ChildException` to `raise ParentException` - you will have to traverse the inheritance tree and produce a mutation for every parent class until (including) you reach `Exception`. There are examples in the code how to generate multiple mutations for a single operator.
* `raise SomeException` to `raise TotallyAnotherException` - I think `TotallyAnotherException` must be something that Cosmic Ray provides so that we make sure we are indeed raising a completely different exception type. However if we go this approach you have to figure out how to inject the `CosmicRayMutationPlaceholderException` into the address space of the mutated modules. I'm not sure how to do this, maybe we only need to import it above all the AST modifications code? @abingham any ideas ?
```
    switch between:
    raise SomeException .... raise AnotherException
    to change into:
    raise AnotherException .... raise SomeException
```

I don't really understand this one. Can you explain? 

Also feel free to create other issues or separate PRs for each of the 3 items above. It's best to implement a small chunk of changes so we can review and test it out instead of waiting longer to have everything completed and then review and test. I will also recommend this approach b/c I'm not quite certain if exceptions mutations won't reveal shortcomings in Cosmic Ray's current design.

**Comment by abingham** [comment]
> It's best to implement a small chunk of changes

This is great advice. It sounds like you're looking at 2 or 3 operators - maybe `ReplaceWithParentException`, `ReplaceWithUnrelatedException`, and `SwapExceptions` (though I'm dubious about this last one...a concrete example would help). I'd start with one and go from there.

> figure out how to inject the CosmicRayMutationPlaceholderException into the address space of the mutated modules

I'm not sure the best way to approach this mutation. My initial reaction is to replace the exception with another exception that already exists in the scope of the original. This way we don't need to try to sneak another one in. Since `__builtin__` provides all of the standard exceptions types for free, we could just pick amongst those. But if this approach turns out to have problems we'd have to think of something more exotic.

**Comment by drorasaf** [comment]
@atodorov , I will create a PR for each. 

I'm still trying to figure it out on how should I try to implement `SwapExceptions`, since as part of the operator I do not have any awareness of the rest of the ast. Am I missing something? any ideas?

> I'm dubious about this last one

The lecture mentioned earlier, shows that several issue found were several errors triggered which cause this situation. this leads to the need of triggering several errors in standard workflow to see the outcome.

@abingham , IMHO, these 3 operators are the basic ones, do you have any other interesting mutations in mind?

**Comment by abingham** [comment]
> do you have any other interesting mutations in mind?

Issue #93 has a list of operators that I'd like to implement. They aren't specific to exceptions, but there are a few operators that deal with them. Feel free to try any of them (which are not already implemented).

**Comment by drorasaf** [comment]
Should I create a different repo for each or should I implement it at a fork and create a PR?

**Comment by abingham** [comment]
> I'm still trying to figure it out on how should I try to implement SwapExceptions, since as part of the operator I do not have any awareness of the rest of the ast. Am I missing something? any ideas?

This is a tricky topic. An operator could, I believe, "remember" the parts of the AST it's already visited. It could use that memory to do these kinds of "non-local" mutations. But this isn't something that we do yet, so don't have any good advice in that area. I would say, though, that it goes against the grain of the normal notion of mutation testing where only small, local changes are introduced.

`SwapExceptions` could be very difficult to implement in any practical way. Taken at it broadest definition, you end up swapping every exception in the program with every other, leading to n-squared growth in the number of mutations. I don't think this is what you're proposing (and it wouldn't work in CR anyway), but even within a single module the growth of mutations could get out of hand. If the operator searched for specific "pathological" relationships between exceptions, though, it could be very powerful.

**Comment by abingham** [comment]
> Should I create a different repo for each or should I implement it at a fork and create a PR?

For the operators on that list I think we'll eventually want to merge them into CR. So feel free to use whichever approach you like for development, but ultimately we'll want to use fork-PR.

**Comment by drorasaf** [comment]
@abingham , I agree that `SwapExceptions` is too complex, I will not implement it, although your remark regarding "pathological" relationships between exceptions is interesting, do you have any material/articles/videos on such relations?

**Comment by abingham** [comment]
> do you have any material/articles/videos on such relations?

No, I'm just saying that the operator might be useful if you (or someone) identified relationships between pairs of exceptions that might warrant swapping them during mutation testing. I actually have no concrete example of if/when this would be a good idea.

However, @atodorov seems to have a much better grasp on the research and literature in the mutation testing field than I do. Perhaps he can motivate a "swap exceptions" operator in concrete terms.

**Comment by drorasaf** [comment]
My current research lead me to the following conclusions:1
1. Swap exceptions is too problematic - high order mutation might come in handy to provide an alternative
2. Change exception to its parent is redundant.
3. Change exception to a totally different, for now I will start with using buiot in exception, and switch between parent errors. example: ArithmeticError ->OSError, OSError ->ArithemticError.

**Comment by abingham** [comment]
I think we're on the right track with exception mutations. Do you mind if I close this issue? We can handle specific operators, etc. in their own issues and PRs.
