### ISSUE TITLE
Suggestion: Print out expected runtime at start and allow user to confirm.

### ISSUE THREAD

**Issue by dougthor42** [sixty-north/cosmic-ray#220]
We all know that cosmic-ray can take a **long** time to run. It would be nice if there was a prompt at the start of `cosmic-ray exec` that gave the user an estimated time-to-run and asked if they want to continue or not.

The estimated runtime could be calculated by:

```
time_of_unmutated_tests * baseline_multiplier * number_of_mutations_to_run
```

The user might see something like this:

```
$ cosmic-ray init --baseline=2 test_session my_pkg -- my_pkg_tests
Created 2368 mutations to Test.
$ cosmic-ray exec test_session
Running tests on unmutated code... Done. 19.76s
Mutation testing can take a very long time to run, growing exponentially on larger projects.
Based on the 2368 mutations, a unittest time of 19.76s, and baseline=2, mutation
testing is estimated to take at most 26hrs to run.
Do you want to continue? [y/N] 
```

Color (via [colorama](https://pypi.python.org/pypi/colorama) or other cross-platform terminal coloring package) could be used for emphasis on the time.

**Comment by abingham** [comment]
Hmm, this is an interesting one. On the one hand, "industrial" users of CR (e.g. people with CR plugged into their automated systems) won't want this; they already know that it takes a long time to run and won't benefit from CR asking them questions. On the other hand, inexperienced users might find the information useful. 

My tendency, as you might expect from my comments in other threads, is to favor simplicity in central commands like `init` and `exec`. As such, I prefer that `exec` just gets about it's business without trying to hand-hold the user. New users might be surprised that CR is taking longer than they expected, but if mutation testing is to be of any real benefit to them they'll need to educate themselves on it. In doing so, one of the first thing they'll learn is that it takes a long time.

I agree, though, that being able to estimate run-time is potentially very useful. I think a standalone tool based on `cosmic-ray dump` (currently only in the `report-rework` branch) is the way to go here. One problem with that approach right now is that `dump` doesn't report the so-called "work parameters", i.e. the session information which includes the timeout.

**Comment by abingham** [comment]
> The estimated runtime could be calculated by: `time_of_unmutated_tests * baseline_multiplier * number_of_mutations_to_run`

I've wondered a bit how to properly calculate and/or report the "expected runtime" of a CR session. The number you're calculating is certainly an upper limit; that number represents the maximum amount of time we'd spend running tests. But generally speaking, I'd expect most tests of mutated code to run in *less* than `time_of_unmutated_tests` simply because I'd expect the test suite to fail somewhere in the middle. We endeavor to end test runs after the first failure, so the actual overall runtime will often be less than `number_of_mutations_to_run * time_of_unmutated_tests`...I think...it's not a simple topic.

Ultimately it's probably best to report an estimate range to the users: maximum runtime and "100% survival rate" runtime.

**Comment by dougthor42** [comment]
> "industrial" users of CR won't want this

100% agree. Most people would think to just add a CLI flag like `--force` or `-y, --yes`, but since the default is already to start running, the would be a lot of users who update and don't realize they have to change their scripts. Definitely not the ideal case.

**I redact my request for a yes/no continue prompt.** *I think it would be sufficient to show the expected time and tell the user to CTRL-C to abort early.*

Then new users know it'll take a while and the experienced users don't have to change any scripts.

> Ultimately it's probably best to report an estimate range to the users: maximum runtime and "100% survival rate" runtime.

How is maximum runtime different from 100% survival rate runtime? Shouldn't those be the same?

----

Also, I had a typo in the original post. I mistakenly said `at least 26hrs` instead of `at most 26hrs`. I've fixed the OP.

----

> favor simplicity in central commands like `init` and `exec`. As such, I prefer that `exec` just gets about its business without trying to hand-hold the user.

For the most part, I agree. But even the simplest of commands (that I'm aware of), provide a little bit of information based on what they're doing. How do you feel about adding a simple time calc and displaying that?

**Comment by abingham** [comment]
> How do you feel about adding a simple time calc and displaying that?

I'd be fine with that. I can't think of any problems it would introduce, and if it does cause any problems it'll be easy to remove. And as you say, it's an interesting bit of information for users

> How is maximum runtime different from 100% survival rate runtime? Shouldn't those be the same?

"Maximum runtime" would be a situation where every mutation resulted in tests that timed out. 100% survival rate will be a situation where every mutation results in a passing test suite. Since timeouts will often be some multiple (> 1) of baseline timing, this "all timeouts" case will be longer in general than the "all surviving" case. It's not guaranteed, of course. Someone could, in principle, choose a timeout which is less than the baseline timing, but this seems like a mistake (and perhaps something we should warn about).

**Comment by dougthor42** [comment]
Yeah, estimating time-to-completion has been a thorn in programmer's side since the beginning. I think that if CR says something to the effect of "Assuming 1 core / non-distributed testing, we estimate that mutation testing will take a max of X hrs.", that will be more than sufficient.

> "Maximum runtime" would be a situation where every mutation resulted in tests that timed out. 100% survival rate will be a situation where every mutation results in a passing test suite.

Ah, I understand now. Thanks.

Thanks for the all the feedback and info 👍

**Comment by rlgomes** [comment]
One thing to consider is using click and the progressbar contextmanager one can get a pretty good estimate of how much time is left to run http://click.pocoo.org/5/utils/#showing-progress-bars and at least give a good estimate after a few seconds of how long is left.

**Comment by rob-smallshire** [comment]
I have a strong preference for the principle of "silence is golden". I don't want successful invocations of command-line programs to report anything (especially on stdout) without being specifically asked to be more verbose.

http://blogs.lt.vt.edu/cdorick/2013/10/21/silence-is-golden/

**Comment by abingham** [comment]
My tendency is certainly towards default silence as well.
