### ISSUE TITLE
Publish plugins to PyPI

### ISSUE THREAD

**Issue by ulope** [sixty-north/cosmic-ray#308]
Please also publish the "bundled" plugins to PyPI. Having to manually install from a Github URL isn't very usable.

**Comment by abingham** [comment]
Right, thanks for reminding me! I'm still sorting out all the deployment
issues, etc. with the plugins.

**Comment by rob-smallshire** [comment]
Will the plugins be installable using the extras_require facility in setuptools, so we can do:

```
pip install cosmic_ray[pytest]
```

Bonus points if the main `setup.py` can enumerate the plugins available on PyPI.

**Comment by abingham** [comment]
That might be the way to go. I haven't looked at the mechanics of it much yet. The main thing we need to ensure is that the plugins can be installed independent of one another. This is especially important for the celery3 and celery4 execution engines since they have different celery dependencies which, afaik, can't co-exist. Generally speaking, we need to assume that different plugins have potentially incompatible dependencies.

**Comment by blueyed** [comment]
I've tried to add the plugins to `extras_require` (for the existing `test` extra), but this does not work when using the file system, even after patching `packaging` (https://github.com/pypa/packaging/pull/115).

For this it would be good to have them on PyPI, but then on the other hand you do not want the version from PyPI when testing/hacking on the plugins yourself.
But then it is easy to `pip install -e` them on top from the source.

**Comment by abingham** [comment]
All things considered, it looks like the right thing to do is to publish the plugins to PyPI. Then we could make the individual plugins installable as `extra_requires` as @rob-smallshire suggested, e.g. `pip install cosmic_ray[pytest_runner]` or something. As @blueyed mentioned, this might be slightly inconvenient for developers, but it's easy enough to install our local version when we need to.

**Comment by abingham** [comment]
This is fixed in 8236465a23dc0603715827ab5f8b18e3fc930814
