### ISSUE TITLE
Line numbers in diff are off

### ISSUE THREAD

**Issue by blueyed** [sixty-north/cosmic-ray#312]
Given the following report, the line number in the diff is way off (293 + 3) - although there is known information about the actual line number (357).

Could the known `line_number` be used to make the one in the diff more accurate?  (I assume it might be still off by +/- 3, since AST is used here instead of the code itself AFAIK)?

```
{
  "data": [],
  "test_outcome": "survived",
  "worker_outcome": "normal",
  "diff": [
    "--- mutation diff ---",
    "--- a…/src/covimerage/covimerage/__init__.py",
    "+++ b…/src/covimerage/covimerage/__init__.py",
    "@@ -293,7 +293,7 @@",
    "                 if next_line.startswith('count'):",
    "                     break",
    "             return skipped",
    "-        for line in file_object:",
    "+        for line in []:",
    "             plnum += 1",
    "             line = line.rstrip('\\r\\n')",
    "             if (line == ''):"
  ],
  "module": null,
  "operator": "cosmic_ray.operators.zero_iteration_loop.ZeroIterationLoop",
  "occurrence": 9,
  "line_number": 357,
  "command_line": null,
  "job_id": null
}
```

**Comment by abingham** [comment]
You're right that the discrepancy comes from the fact that base the diff on the AST. In `cosmic_ray.worker.worker()` we unparse both the unmodified and modified ASTs, and we run that source into the differ. 

We might be able to use `WorkItem.line_number` to improve this. However, my inclination right now is to leave this until we deal with #281 and #310, i.e. until we use a mutation method that operates on source code itself. Once we have *that* in place, I figure calculating more accurate diffs will be trivial (since it won't involve unparsing, etc.)

However, if you want to patch this up right now to try to use `line_number`, feel free. I don't know how easy/elegant that will be, though, since I think you'll need to basically parse and modify the text lines produced by the differ.
