### ISSUE TITLE
PyCharm link

### ISSUE THREAD

**Issue by LLKoder** [sixty-north/cosmic-ray#440]
Html report has a PyCharm link - pycharm://open?file=calculator.py&line=2.

Unfortunately, I cannot find a description of this function in PyCharm's manual.

Please tell me, what is this link for? It doesn't work for me.
Maybe does it work for Unix/Linux only? I have Windows.

**Comment by abingham** [comment]
It may just not work on windows. I tried it, and windows doesn't seem to know what to do with it. Maybe there's something you need to do during PyCharm installation, or perhaps there's some sort of setting in pycharm itself that can activate this.

Interestingly, these links on seem to half-work in macos. If you click them they try to open a file in pycharm, but since the links don't contain absolute paths, pycharm doesn't seem to know how to find the files. We should probably be using absolute paths.

I'll close this, but go ahead and re-open it if you feel like following up on it.

**Comment by abingham** [comment]
Here's a discussion about why this doesn't work automatically, how to make it work (in principle), etc.: https://youtrack.jetbrains.com/issue/IDEA-65879
