### ISSUE TITLE
More result status in the report.

### ISSUE THREAD

**Issue by LLKoder** [sixty-north/cosmic-ray#444]
I have been used CR for some time and I want to suggest/discuss one feature for a report.

Now in the report are two status of a job. There are SURVIVE and KILLED. More precisely there is one status `result.is_killed`. It's a boolean.

I fully understand SURVIVE status, SURVIVE status shows users only what tests are survived.
Contrariwise, KILLED status shows users three actions/errors. It shows what tests are KILLED or TIMEOUT (CR timeout) or CRASHED (crash CR, crash user's test, crash user's code). Three absolutely different actions/errors in one status - KILLED.

IMHO one status has to consist of one action/error.
My suggestion divide the KILLED status at three status (KILLED, TIMEOUT, CRASHED), and make four status: SURVIVE, KILLED, TIMEOUT, CRASHED.

The added status will do the report very light for understanding and the report will be more informative.

What do you think about this idea?

**Comment by abingham** [comment]
I'd be fine with adding more detailed information to the report if it's
necessary. I've got a few thoughts about what you've described.

First, we don't have to rely on the `is_killed` method. I added that a way
to centralize the concept of "did a mutant survive or not" since this is
the primary question CR is trying to answer. That is, assuming that CR is
working properly, then (I assume) most users will be asking one question:
how many survivors did I have? How mutants get killed - timeout,
incompetence, or test failure - is largely irrelevant. So feel free to use
the `test_outcome` field of `WorkResult` if you want to discriminate
between "killed" and "incompetent", for example.

Second, we already have, I think, a good indicator of whether a mutant
timed out. The `output` field of `WorkResult` will say "timeout",
explicitly indicating that CR killed it. I'm not sure what we gain by e.g.
extending the `TestOutcome` enum with an explicit "timeout" value, but I'm
open to persuasion.

Next, I think what you're calling "crashed" is really our existing
"incompetent" test outcome. These are tests that won't even run for some
reason. It's fine with me if you want to put "incompetent" in the report
for these mutants.

Finally, I'd like to avoid adding special handling for the case where CR
itself is misbehaving. I'm not entirely sure that you're suggesting that,
but it seems like a dangerous road to go down. If CR is broken, then I
wouldn't generally trust it's ability to detect that it's broken, and I
don't want to put energy into solving unsolvable problems. You're
absolutely right that there will be times when CR is broken, but that's a
problem for developers. Generally these kinds of problems show up loud and
clear in the test results, and the results contain enough information for
humans to start sorting out the problem.

So if I can summarize:
1. It would be great if you want to point out incompetent mutants in the
report.
2. It would also be great if you want to highlight timeouts somehow, but I
think we can do that without inventing a new work result type.
3. I don't want to spend time building functionality for detecting if CR
itself is broken; that a job for developers.
4. The primary purpose of reports is to show users their survivors, and I
don't want to make that harder for them.

**Comment by LLKoder** [comment]
Well, It seems I see you.

> How mutants get killed - timeout, incompetence, or test failure - is largely irrelevant. 

IMHO it's important information. So I had the case with the killed (green) test (indeed it was a syntax error) then I fix it I see survived (red) test.

Another example, please look at the attached file.

I'm a user. I occasionally do syntax error in `calculator.py`... `!return x * y` Then I run CR and look at the report. And what do I see? All test are killed/green. I'm happy that the whole code is covered by test... BUT... it's not so... It's just syntax error. And CR understands it as a killed test.
In this case, I have 12 jobs. but there may be thousands in another case. And the user will not able to look at each job. And he will not understand that he will only have a half true report. I understand he will see syntax error when he will apart run the tests later, but why cannot tell to the user first about that.

I fully agree with you that the main task of CR is telling the user that the test is survived or not.
But another main task of CR is given to user correctly information. This IMHO.

[tests.zip](https://github.com/sixty-north/cosmic-ray/files/3227857/tests.zip)

**Comment by abingham** [comment]
> I'm a user. I occasionally do syntax error in calculator.py... !return x * y Then I run CR and look at the report.

But you definitely should not be running CR when your test suite doesn't pass on the unmutated code. CR can't tell you anything meaningful in that case. CR assumes that a failing test suite - i.e. the ground state of such code - indicates a kill, so of course you'll see the situation you describe.

> I understand he will see syntax error when he will apart run the tests later, but why cannot tell to the user first about that.

Interestingly, CR used to run the tests over unmutated code during the 'init' phase, and it would abort if the tests failed for exactly this reason. Maybe we should re-add that as an optional step of 'init'.

So, I still think that users won't typically care much about why mutants are killed. I just don't see what they'd do with the information. Aside from the case you mention (where the tests don't pass on unmutated code), what would hope to learn by examining the kills? I may just be missing an important point.

**Comment by LLKoder** [comment]
> But you definitely should not be running CR when your test suite doesn't pass on the unmutated code. CR can't tell you anything meaningful in that case. CR assumes that a failing test suite - i.e. the ground state of such code - indicates a kill, so of course you'll see the situation you describe.

This case and report are confused me as a user and maybe I'm wrong but attached report doesn't consist of correct information. CR doesn't have to mark users' mistake as killed tests. KILLED or SURVIVED test status have to show the results CR's work only, not the results of my work (like a syntax error).

> Interestingly, CR used to run the tests over unmutated code during the 'init' phase, and it would abort if the tests failed for exactly this reason. Maybe we should re-add that as an optional step of 'init'.

Unfortunately, I don't' know the whole code of CR. I think to be two cases to tell the user about his test/code was faulty:
1. Not run CR at all. To show to user fatal error that his test/code doesn't work correctly. (IMHO it's the less friendly case).
2. To tell the user about this case in the report and to change the status of this job to error status. (it's the more friendly case, 'cause the other jobs may be correct and he can see at least them).

> So, I still think that users won't typically care much about why mutants are killed. I just don't see what they'd do with the information. Aside from the case you mention (where the tests don't pass on unmutated code), what would hope to learn by examining the kills? I may just be missing an important point.

And you know you are right. Users don't need more information it will be enough if CR will have 3 status: SURVIVED, KILLED, OTHER=INCOMPETENT (the last status consist all error about not correctly CR's work: timeout, crashed user's code/test or other error).

IMHO only have to move my case to INCOMPETENT instead KILLED.

**Comment by abingham** [comment]
> KILLED or SURVIVED test status have to show the results CR's work only, not the results of my work (like a syntax error).

The problem is that, generally speaking, CR can't discriminate between "user mistakes" and "CR's work". CR may make a change in one part of the code that causes the control flow to change in such a way as to trigger a latent "user mistake" somewhere else. Is that the result of CR or the user? And even if we could assign blame in principle, what technology we deploy to make that decision in an automated way?

So I maintain that you should not be running CR unless your test suite passes on unmutated code. If your unmutated code contains a syntax error, there's no way for your test suite to pass, so CR can't do anything useful for you. 

> And you know you are right. Users don't need more information it will be enough if CR will have 3 status: SURVIVED, KILLED, OTHER=INCOMPETENT (the last status consist all error about not correctly CR's work: timeout, crashed user's code/test or other error).

If I understand you correctly, I think you're not considering a large class of mutations. For example, a `timeout` will very often be the direct result of a CR mutation, and it will have nothing to do with user errors. One of CR's mutations is to change "break" with "continue", and this can very easily result in an infinite loop (and thus a timeout). Other CR mutations can lead directly to crashes, exceptions, etc. So you should not equate "incompetent" or "timeout" with "programmer error".

> IMHO only have to move my case to INCOMPETENT instead KILLED.

The problem here is that, again, there's no obvious way for CR to discriminate between what you're thinking of as "user errors" and "CR's work". We use 'incompetent' for situations where we either a) can't start the test process or b) the test process dies without giving us a return code (e.g. via segfault). Assuming the test process executes, we rely on its return code to distinguish between 'survived' and 'killed'. If we wanted to make some finer distinction after receiving an error code, we'd probably need to examine the stdout/stderr of the test process to parse out what happened. This may not be impossible, but it sounds to me like a lot of work for very little gain (also consider that we'd need separate parsing support for each test runner that we support).

In case I'm still missing an important point, though, I'll ask again: what do you hope to gain by creating these finer distinctions between 'killed' and 'survived'? (If the answer is "CR can then tell me if my test suite fails on unmutated code", then my response would be to not run CR on such code bases.)

**Comment by LLKoder** [comment]
> If I understand you correctly, I think you're not considering a large class of mutations. For example, a timeout will very often be the direct result of a CR mutation, and it will have nothing to do with user errors. One of CR's mutations is to change "break" with "continue", and this can very easily result in an infinite loop (and thus a timeout). Other CR mutations can lead directly to crashes, exceptions, etc. So you should not equate "incompetent" or "timeout" with "programmer error".

OK, I see. You have told about an optional step of 'init'. Is it possible?
In any case, it will be better than to show to user incorrect results. Maybe I'm wrong.

I have two small questions about the next add-on:
1. In which case will the number of complete jobs be less number of the total jobs?
2. How can I get (emulate) incompetent jobs for my test of HTML report?

**Comment by abingham** [comment]
> You have told about an optional step of 'init'. Is it possible?

In principle, yes. We used to run the unmutated code to make a baseline timing, but we've done away with that as an unnecessary complication. But I'm reluctant to add it just so that CR can verify the status of the test suite; this is something that should be trivial for the user to do themselves.

>  it will be better than to show to user incorrect results.

This is where I think we disagree. If a test suite is failing on unmutated code, someone simply shouldn't be expecting CR to work. A passing test suite is a prerequisite for CR, and I don't see how it's a burden to ask people to verify this for themselves. I don't think there's really a "right" or "wrong" about this; I'm biased by my need to keep CR simple when possible.

> In which case will the number of complete jobs be less number of the total jobs?

One trivial case will be immediately after you run `init`. You will have zero completed jobs and (generally) some non-zero number of total jobs.

Less trivially, if you kill the `exec` process midway through a run you'll have some number of completion which is less than the total. You can run `exec` again to start where you left off.

> How can I get (emulate) incompetent jobs for my test of HTML report?

This is an interesting question! If you want to have `cosmic-ray exec` produce an incompetent result, I'm not really sure. If you want to just test cr-html itself, you could create a dummy WorkDB, add an incompetent result to it, and then pass that DB to cr-html (or `_generate_html_report` if you want to work at that level).

**Comment by LLKoder** [comment]
Thanks a lot for explanations. I'll try to create the next add-on.
