### ISSUE TITLE
Cosmic Ray doesn't start

### ISSUE THREAD

**Issue by flomotlik** [sixty-north/cosmic-ray#448]
When installing the latest version either in Docker or on my host the following exception is thrown:

```
Traceback (most recent call last):
  File "/usr/local/bin/cosmic-ray", line 6, in <module>
    from cosmic_ray.cli import main
  File "/usr/local/lib/python3.7/site-packages/cosmic_ray/cli.py", line 67, in <module>
    doc_template=DOC_TEMPLATE)
TypeError: __init__() got an unexpected keyword argument 'version'
```

I'm not sure what the specific issue here is, but could send a PR if you clear up that question.

**Comment by abingham** [comment]
The problem is almost certainly related to changes in the
docopt_subcommands API. CR needs to specify the correct version range in
its setup. I'll try to sort that out soon.

If you want to brute-force past this for now, you can `pip uninstall
docopt_subcommands` and then `pip install docopt_subcommands==3.0.0`. This
*should* get things working.

If you've got the time to create a PR that sets the correct version in
setup.py, that would be awesome. Thanks for reporting this!
